name: Local Pipeline Demo

on:
  push:
    paths:
      - 'local-pipeline-demo/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t local-pipeline-demo ./local-pipeline-demo
      - name: Run Docker container
        run: docker run --rm local-pipeline-demo
