name: Local Pipeline Demo

on:
  push:
    paths:
      - 'local-pipeline-demo/**'

jobs:
  lint:
    name: Lint Python code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install flake8
        run: pip install flake8
      - name: Lint Python code
        run: flake8 local-pipeline-demo/src

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t local-pipeline-demo ./local-pipeline-demo
      - name: Run Docker container
        run: docker run --rm local-pipeline-demo
